// Auto-generated by scripts/generate-search-index.mjs
// Do not edit manually. Run `node scripts/generate-search-index.mjs` to regenerate.

import type { SearchDoc } from "./content";
import type { Locale } from "./i18n";

// @ts-nocheck
import zhIndex from "../public/search-index-zh.json";
import enIndex from "../public/search-index-en.json";

export const staticSearchIndex: Record<Locale, SearchDoc[]> = {
  zh: zhIndex as SearchDoc[],
  en: enIndex as SearchDoc[],
};
